### ISSUE TITLE
2 problems, and a fix

### ISSUE THREAD

**Issue by agucova** [killdash9/MacClam#1]
I have **2 problems**. (One fixed, one to go)
a) The download address in the code, doesn't work.
Solution: Change
`CLAMAV_DOWNLOAD_LINK="http://nbtelecom.dl.sourceforge.net/project/clamav/clamav/$CLAMAV_VER/clamav-$CLAMAV_VER.tar.gz"`
to
`CLAMAV_DOWNLOAD_LINK="https://www.clamav.net/downloads/production/clamav-$CLAMAV_VER.tar.gz"`
b) **OpenSSL is not found** on /usr (installed via brew, no longer included on 10.11)
I got this on the ./configure part (probably)
`checking for OpenSSL installation... /usr  
configure: error: OpenSSL not found.`
Brew give this warning, it may help:

> Apple has deprecated use of OpenSSL in favor of its own TLS and crypto libraries
> 
> Generally there are no consequences of this for you. If you build your
> own software and it requires this formula, you'll need to add to your
> build variables:
> 
> ```
> LDFLAGS:  -L/usr/local/opt/openssl/lib
> CPPFLAGS: -I/usr/local/opt/openssl/include
> ```

**Comment by agucova** [comment]
So, after adding a 
`-with-openssl=/usr/local/opt/openssl` to the ./configure command, it worked.
BTW: Yes, it's one dash, idk why it worked, maybe is case insensitive.

**Comment by killdash9** [comment]
Thank you.  I will incorporate your fixes.  Sorry for the long delay.

**Comment by killdash9** [comment]
It now builds and runs on Mojave.  I ended up having the install process build openssl from source, the way it does for clamav and fswatch, rather than introduce a dependency on brew.
