### ISSUE TITLE
Add a License

### ISSUE THREAD

**Issue by harens** [killdash9/MacClam#6]
I currently have a [fork](https://github.com/harens/MacClam) with a few additional commits and improvements, although it's uncertain about the legality of this since there's no license (see https://github.com/harens/MacClam/pull/2).

@killdash9 has been contacted about this issue via email.

**Comment by killdash9** [comment]
I've added an MIT license into the master branch.  I have no issues with you making improvements to this code.  I haven't had the time or desire to maintain it.
